### ISSUE TITLE
Frontend Flow Chart

### ISSUE THREAD

**Issue by drakedel** [ubet-app/administrative#2]
[Frontend Flow Chart.pdf](https://github.com/ubet-app/administrative/files/4400127/Frontend.Flow.Chart.pdf)
Front end flow chart needs to be reviewed by P and will continually be updated as changes are made to the overall design. https://app.diagrams.net/#G18RqhCOdAMwCND66RbB66vST4gQ2tparw

**Comment by pmarks98** [comment]
@drakedel I don't have access to the file - can you check if link sharing is turned on?

**Comment by pmarks98** [comment]
@drakedel I cleaned up the diagram

**Comment by pmarks98** [comment]
Closing Issue per above progress.
