### ISSUE TITLE
Determine what Sports API to use. Relay that to Drake and determine the cost and how to best use that data.

### ISSUE THREAD

**Issue by pmarks98** [ubet-app/administrative#3]
I decided to go with SportsData.io as it seemed the best for sports data but couldn't find pricing or anything for this API. It gives a lot of flexibility with information and stuff for future other types of sports and if we need other information than just game scores. 

If you want to give it a look or see if you find other ones that would be better/more cost effective, let me know.

**Comment by drakedel** [comment]
I have contacted sportsdata.io and goalserve.com to see how long of a free trial they would be willing to provide during development and what costs would be once we launch.

**Comment by drakedel** [comment]
sportsdata.io seems like a top dog in the industry but goalserve.com seems to have much lower prices than many competitors
Some listed prices from other APIs list costs at $2000/month for realtime data whereas goalserve.com shows prices at around $2400/year

**Comment by pmarks98** [comment]
I found a way to get NFL scores but just I don't know how quickly they are updated (if in real-time or not). It has all historical scores in XML format which I could send requests to and parse the information we need: http://www.nfl.com/ajax/scorestrip?season=2019&seasonType=REG&week=1

**Comment by drakedel** [comment]
Okay we can use that for now

**Comment by drakedel** [comment]
Goalserve Email

Hello Drake

Thank you for your email.

We provide free 30 days free trial. If you want to setup please register on our website and send us your login name so we can proceed.

US Sports package price is $400 per month

https://www.goalserve.com/en/sport-data-feeds/ussports-api/prices

Package include

NFL
NCAAF
XFL
CFL
NBA
NCAAM
MLB
NHL
WNBA
WNCAA
NASCAR
PGA
MLS Soccer (EPL, UCL, World Cup leagues are also included)
[xmlcoverage[7141].pdf](https://github.com/ubet-app/administrative/files/4419689/xmlcoverage.7141.pdf)
[Live MLB stats[7140].pdf](https://github.com/ubet-app/administrative/files/4419690/Live.MLB.stats.7140.pdf)
[Live NFL stats[7139].pdf](https://github.com/ubet-app/administrative/files/4419691/Live.NFL.stats.7139.pdf)

**Comment by drakedel** [comment]
SportDataIO Email

Drake,

Thanks for getting in touch.

SportsDataIO's free trials never expire. However, the data delivered by trial keys are delayed and scrambled. We could certainly discuss "enhanced" trial keys that function just like production keys.

In terms of costs, data licenses are typically $5,000-$10,000 per league, per season. 

Do you have a few minutes in the coming days to connect and discuss your project?

**Comment by pmarks98** [comment]
Perfect - we'll just use that NFL URL for right now but looks like goalserve might be good for us in the future.
